[build]
  publish = "."

[[redirects]]
  from = "/connect"
  to = "https://blinq.me/cmjbcm89k0ljvs60m2va3lubh?bs=icl"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/connect"
  status = 301
  force = true

[[headers]]
  for = "/projects/*"
  [headers.values]
    Basic-Auth = "mcmclient:MCM-Projects-2026!"
    X-Robots-Tag = "noindex"
